### ISSUE TITLE
OutOfMemory

### ISSUE THREAD

**Issue by jamen** [Keavon/Graphite#1]
Hi. I tried running this on Windows

```
cargo build
RUST_BACKTRACE=1 ./target/debug/Graphite.exe 
```

But it fails

```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: OutOfMemory(Host)', C:\Users\jamen\.cargo\registry\src\github.com-1ecc6299db9ec823\wgpu-core-0.5.6\src\device\mod.rs:1822:17
stack backtrace:
   0: backtrace::backtrace::trace_unsynchronized
             at C:\Users\VssAdministrator\.cargo\registry\src\github.com-1ecc6299db9ec823\backtrace-0.3.46\src\backtrace\mod.rs:66
   1: std::sys_common::backtrace::_print_fmt
             at /rustc/49cae55760da0a43428eba73abcb659bb70cf2e4\/src\libstd\sys_common\backtrace.rs:78
   2: std::sys_common::backtrace::_print::{{impl}}::fmt
             at /rustc/49cae55760da0a43428eba73abcb659bb70cf2e4\/src\libstd\sys_common\backtrace.rs:59
   3: core::fmt::write
             at /rustc/49cae55760da0a43428eba73abcb659bb70cf2e4\/src\libcore\fmt\mod.rs:1069
   4: std::io::Write::write_fmt<std::sys::windows::stdio::Stderr>
             at /rustc/49cae55760da0a43428eba73abcb659bb70cf2e4\/src\libstd\io\mod.rs:1504
   5: std::sys_common::backtrace::_print
             at /rustc/49cae55760da0a43428eba73abcb659bb70cf2e4\/src\libstd\sys_common\backtrace.rs:62
   6: std::sys_common::backtrace::print
             at /rustc/49cae55760da0a43428eba73abcb659bb70cf2e4\/src\libstd\sys_common\backtrace.rs:49
   7: std::panicking::default_hook::{{closure}}
             at /rustc/49cae55760da0a43428eba73abcb659bb70cf2e4\/src\libstd\panicking.rs:198
   8: std::panicking::default_hook
             at /rustc/49cae55760da0a43428eba73abcb659bb70cf2e4\/src\libstd\panicking.rs:218
   9: std::panicking::rust_panic_with_hook
             at /rustc/49cae55760da0a43428eba73abcb659bb70cf2e4\/src\libstd\panicking.rs:511
  10: std::panicking::begin_panic_handler
             at /rustc/49cae55760da0a43428eba73abcb659bb70cf2e4\/src\libstd\panicking.rs:419
  11: core::panicking::panic_fmt
             at /rustc/49cae55760da0a43428eba73abcb659bb70cf2e4\/src\libcore\panicking.rs:111
  12: core::option::expect_none_failed
             at /rustc/49cae55760da0a43428eba73abcb659bb70cf2e4\/src\libcore\option.rs:1268
  13: core::result::Result<gfx_backend_vulkan::native::GraphicsPipeline, gfx_hal::pso::CreationError>::unwrap<gfx_backend_vulkan::native::GraphicsPipeline,gfx_hal::pso::CreationError>
             at C:\Users\jamen\.rustup\toolchains\stable-x86_64-pc-windows-msvc\lib\rustlib\src\rust\src\libcore\result.rs:1005
  14: wgpu_core::hub::Global<wgpu_core::hub::IdentityManagerFactory>::device_create_render_pipeline<wgpu_core::hub::IdentityManagerFactory,gfx_backend_vulkan::Backend>
             at C:\Users\jamen\.cargo\registry\src\github.com-1ecc6299db9ec823\wgpu-core-0.5.6\src\device\mod.rs:1822
  15: wgpu_native::device::wgpu_device_create_render_pipeline
             at C:\Users\jamen\.cargo\registry\src\github.com-1ecc6299db9ec823\wgpu-native-0.5.1\src\device.rs:339
  16: wgpu::Device::create_render_pipeline
             at C:\Users\jamen\.cargo\registry\src\github.com-1ecc6299db9ec823\wgpu-0.5.2\src\lib.rs:867
  17: graphite::pipeline::Pipeline::build_pipeline
             at .\src\pipeline.rs:111
  18: graphite::pipeline::Pipeline::new
             at .\src\pipeline.rs:30
  19: graphite::application::Application::new
             at .\src\application.rs:72
  20: graphite::main
             at .\src\main.rs:30
  21: std::rt::lang_start::{{closure}}<()>
             at C:\Users\jamen\.rustup\toolchains\stable-x86_64-pc-windows-msvc\lib\rustlib\src\rust\src\libstd\rt.rs:67
  22: std::rt::lang_start_internal::{{closure}}
             at /rustc/49cae55760da0a43428eba73abcb659bb70cf2e4\/src\libstd\rt.rs:52
  23: std::panicking::try::do_call
             at /rustc/49cae55760da0a43428eba73abcb659bb70cf2e4\/src\libstd\panicking.rs:331
  24: std::panicking::try
             at /rustc/49cae55760da0a43428eba73abcb659bb70cf2e4\/src\libstd\panicking.rs:274
  25: std::panic::catch_unwind
             at /rustc/49cae55760da0a43428eba73abcb659bb70cf2e4\/src\libstd\panic.rs:394
  26: std::rt::lang_start_internal
             at /rustc/49cae55760da0a43428eba73abcb659bb70cf2e4\/src\libstd\rt.rs:51
  27: std::rt::lang_start<()>
             at C:\Users\jamen\.rustup\toolchains\stable-x86_64-pc-windows-msvc\lib\rustlib\src\rust\src\libstd\rt.rs:67
  28: main
  29: invoke_main
             at d:\A01\_work\6\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:78
  30: __scrt_common_main_seh
             at d:\A01\_work\6\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:288
  31: BaseThreadInitThunk
  32: RtlUserThreadStart
```

Is this a bug or am I missing something?

Same thing in release mode.

Seems like it points to [this line in graphite's code](https://github.com/Keavon/Graphite/blob/6a94905f61ecbc6d2ab8bd30c90b6245612b13bd/src/pipeline.rs#L111). But I have a similar pipeline in my project without this issue.

Edit: I tried compiling and loading the shaders manually with `glslc` from `shaderc` but its the same error.

**Comment by Keavon** [comment]
That's very strange. I just cloned the repo entirely from scratch and ran `cargo run` and it downloaded all the dependencies, compiled, and ran fine. There shouldn't be any other steps I can think of. I'll try the same on my laptop.

**Comment by Keavon** [comment]
I've tried the same on my laptop and it seems to work fine also. What are your system specs? I'll have to ask the WGPU folks if this might be a bug on their end, or if my code is doing something that causes device-specific (mis)behavior.

**Comment by jamen** [comment]
I've got Windows 10.0.18363, Ryzen 5 2600 cpu, RX 580 gpu

**Comment by Keavon** [comment]
I found the problem (I was using as sampler2D for simplicity instead of a sampler and a texture2D, but apparently that's not really allowed). Working on a fix now. Thanks for reporting this!

**Comment by Keavon** [comment]
That should do it! Let me know if things are working on your end now. At the moment I'm in the process of building the logic that powers the GUI tree (i.e. the DOM) so it's just printing out the layout XML files (so there's not much to see yet when you compile). I'll be hooking that up to draw actual rectangles to the screen in the coming weeks. Let me know if you're interested in collaborating.

**Comment by jamen** [comment]
Yup, it works!

I love the concept and I'd like to collaborate. But I'm also learning graphics programming, so I have no wisdom to bring.

**Comment by Keavon** [comment]
Wonderful! I am also new to graphics programming in Rust (and Rust in general).

But it's clear to me that this is the perfect time in history to begin the project now that Rust and WGPU are becoming mature and they are both crucial technologies to building a really high quality piece of software to realize the goals of the perfect image editor. Low-level, no memory leak bugs, lots of checks on code correctness, the easy ability to port the same code to all platforms even including the web, easy multithreading, and potentially the ability to have a correctness guarantee against software crashes in most scenarios. My goal is to architect it so all operations are run in a separate thread that can always be instantly aborted by hitting <kbd>Escape</kbd> so the program is built to be freeze-proof, with a way to always save your work even if the program has to reload any major components or the whole software to recover from an erroneous state. Anyways, that's a bit more about my thoughts on why Rust is so exciting to be learning now and using for this project.

So even if you're new to graphics programming, your Rust experience and doubling of manpower would be extremely helpful! Do you use Discord?—that would be a great place to start collaborating.
