### ISSUE TITLE
Better GUI code error reporting

### ISSUE THREAD

**Issue by GabrielMajeri** [Keavon/Graphite#11]
One important UX improvement for GUI component authors is providing clear and understandable error messages.

For now, we can just panic if the XML is invalid in any way.

The best solution is to use a crate like [codespan](https://github.com/brendanzab/codespan), which would allow us to emit nicely formatted errors, just like the Rust compiler.

**Comment by Keavon** [comment]
Shelved on account of switching to a web app frontend for the short term.
