### ISSUE TITLE
Scripting Language: What about WASM instead?

### ISSUE THREAD

**Issue by jakeswenson** [Keavon/Graphite#16]
# Discussion
I know this might be early but I just stumbled on to this project (great work by the way) and noticed that you plan to support scripting via javascript. That probably makes sense, but I wanted to at least throw out a thought I've been having about scripting for my projects and that's using WASM instead of Lua/javascript. This would allow any language that compiles to WASM to be used for scripting...

Just a thought for the owner(s). Sorry if this is too early or too late, just trying to share an idea!

# Resources
[Rust, WebAssembly, and the future of Serverless by Steve Klabnik](https://www.youtube.com/watch?v=CMB6AlE1QuI)

**Comment by Keavon** [comment]
Thanks for the suggestion! I did briefly ponder it but I figured that a real scripting language would be more powerful and user-friendly. However there are certainly advantage of using WASM like not having to include the whole hefty V8 engine. I will do some more research into that front and make a decision about JS versus WASM, or perhaps both if V8 already makes that easy to include.

**Comment by Keavon** [comment]
After some discussions today, we've chosen to go with WASM for this. The first step is defining and building an API that the WASM code for each GUI component will use, then implementing the API. To save time, components that use that API will first be written in Rust (including, of course, the primitive components that directly control the layout, icon/text texture rasterization, and quad rendering). The dual-use API can then support WASM plug-in GUI component code later down the road, but this also helps keep more code as native Rust.
