### ISSUE TITLE
Use `log` instead of `println`

### ISSUE THREAD

**Issue by GabrielMajeri** [Keavon/Graphite#17]
There are a few temporary `println`s throughout the code, which are very useful now, in the early stages of the project, to make sure everything gets loaded and runs correctly.

We could instead switch to the [`log`](https://docs.rs/log/) crate, and use appropriate (`trace`, `debug`, `info`) levels.

**Comment by Keavon** [comment]
Shelved on account of switching to a web app frontend for the short term.
