### ISSUE TITLE
How to contribute?

### ISSUE THREAD

**Issue by GabrielMajeri** [Keavon/Graphite#2]
Hi, the project's vision described in the readme is really cool. However, there aren't a lot of open issues.

Since the readme says

> The project is seeking collaborators to help design and develop the software.

would it be possible to get an idea in which stage the project is, and how we can help?

**Comment by Keavon** [comment]
Hello, I'm very glad to hear you are interested! I was envisioning at least a year of lone development before I could convince anyone else to help me with development but I've been blown away by its reception so far. I haven't been using issues to direct feature development yet but that might not be a bad idea in the near future. Do you use Discord? I just created a server to coordinate with interested collaborators. Here's a link you (and anyone else) can use to join. To prevent spam, remove all the hyphens: `https://dis-co-rd.gg/v-KN-N-w-6r`

**Comment by GabrielMajeri** [comment]
Closing this since there's been some discussion on Discord, and there are also issues describing what needs to be done.
