### ISSUE TITLE
Implement layout algorithm

### ISSUE THREAD

**Issue by GabrielMajeri** [Keavon/Graphite#6]
Once the layout is parsed into memory, we have to compute the offsets and sizes (width/height) of the objects to be rendered.

## Layout algorithm

To calculate dimensions (width/height):
- elements with **fixed** sizes (e.g. `123px`) are laid out, in the order they are encountered.
- then we handle elements with `inner`, which indicates that the size of the component depends on the size of the child.
- then **percentages** (such as `10%`) are computed, based on the total size of the parent container.
- then `@` rules (e.g. `100@`) are applied, which divide up the remaining free space.

When the `width`/`height` attributes are not specified, they each default to `inner`.

To calculate positions (x/y):
- this only makes sense when there is some free space left (otherwise, all the elements fit tightly together and are positioned one after another).
- `x-align`/`y-align` take a percentage, which indicates where it should be along the respective axis.
  `0%` would mean completely to the left/to the top, `100%` would mean completely to the right/to the bottom, and `50%` would be halfway between.

If there's not enough space in the parent container to lay out all children, we need to handle the overflow (for instance, through _scrolling_).

**Comment by Keavon** [comment]
This card refers to this issue: https://github.com/Keavon/Graphite/projects/1#card-41708195

**Comment by Keavon** [comment]
Shelved on account of switching to a web app frontend for the short term.
