### ISSUE TITLE
Enforce standard Rust code formatting

### ISSUE THREAD

**Issue by GabrielMajeri** [Keavon/Graphite#7]
Running the repository through `cargo fmt` ends up reformatting almost all of the files.

Since this can end up being quite messy once the project gets larger, we should do a commit formatting the code now, and keep on using `rustfmt` consistently to keep the code formatted.

**Comment by Keavon** [comment]
Please use either VS Code with Rust Analyzer for format-on-save or the following command line argument to auto-format the project:

```
cargo fmt -- --config match_block_trailing_comma=true --config control_brace_style=ClosingNextLine
```

`match_block_trailing_comma` will become stable when rustfmt 2.0 is released. `control_brace_style` is still unstable. Hopefully both of these can be finalized in the near future to simplify the process.
