### ISSUE TITLE
Extract layout attributes into a separate structure

### ISSUE THREAD

**Issue by GabrielMajeri** [Keavon/Graphite#9]
Right now, the layout attributes (such as `width` or `padding`) are stored together with other, user-defined attributes in the `attributes` vector:
https://github.com/Keavon/Graphite/blob/c41710ab7696799d6d81974eee3768d01c58c60c/src/layout_abstract_syntax.rs#L23
To store these more efficiently, and to simplify the downstream code, the parser should extract these attributes and store them into a Rust structure. Something similar to this:
https://github.com/Keavon/Graphite/blob/c41710ab7696799d6d81974eee3768d01c58c60c/src/layout_dom_node.rs#L8-L12
But instead of `f32`s, width and height would store a `Dimension`.

If the parser notices a node has a value given for a layout attribute, for example `width = "10px"`, it will store it as is (`Dimension::AbsolutePx(10.0)`). Otherwise it will use the default value (in this example, `Dimension::Inner` for unspecified width).

**Comment by Keavon** [comment]
This sounds like a solid assessment of the task at hand. There will also be event binding attributes that look like `on:click="doSomething()"` or `on:mousedown="somethingElse('hello')"`.

Feel free to nuke that all-commented-out file, it's outdated by now.

> Otherwise it will use the default value (in this example, `Dimension::Inner` for unspecified width).

An error is probably better so any syntax mistakes don't get overlooked when writing the XML components.

**Comment by Keavon** [comment]
To clarify what I previously wrote:

>> Otherwise it will use the default value (in this example, Dimension::Inner for unspecified width).
>
> An error is probably better so any syntax mistakes don't get overlooked when writing the XML components.

I was referring to throwing an error when an *invalid* value is set. The default should definitely apply as you suggested when the attribute is entirely missing. Sorry for the misunderstanding when I first read that and replied.
